# Configuration file for the Sitemap extension.

show_listings: false
limit: 10000
templates:
  xml: "@sitemap/sitemap.xml.twig"
  xsl: "@sitemap/sitemap.xsl"
taxonomies: ["nosRealisationsTags"]
#exclude_contenttypes: ["pages"]
#exclude_listings: ["pages"]
