# Settings for Bolt Article

# All options: blockcode, buttonlink, carousel, counter, definedlinks, filelink,
# handle, icons, imageposition, inlineformat, makebutton, print, reorder,
# selector, specialchars, style, tags, textdirection, underline, variable,
# removeformat, imageresize
default:
  plugins: [ blockcode, buttonlink, definedlinks, inlineformat, reorder, tags, underline, imageposition, filelink, removeformat, imageresize]
  source: true
  custom: 
    css: [ '/theme/transvis/css/dependency/customAdminArticle.css' ]
  classes:
    p: 'article-paragraph'
    img: 'img-fluid'
    h1: 'article-h1'
    h2: 'article-h2'
    h3: 'article-h3'
    h4: 'article-h4'
    h5: 'article-h5'
    h6: 'article-h6'
  grid:
    classname: 'row'
    columns: 12
    patterns:
      '4|4|4': 'col-12 col-lg-4|col-12 col-lg-4|col-12 col-lg-4'
      '4|8': 'col-12 col-md-4 col-lg-4|col-12 col-md-8 col-lg-8'
      '6|6': 'col-12 col-md-6 col-lg-6|col-12 col-md-6 col-lg-6'
      '8|4': 'col-12 col-md-8 col-lg-8|col-12 col-md-8 col-lg-4'

  # Settings for images
  # Note: The current editor can only upload / insert images if they are granted 
  # the 'upload' and 'list_files:files' permissions in `permissions.yaml`.  
  image:
    thumbnail: 1000×1000×max

plugins:
  ~
