# This file defines the content types on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

# The Homepage content type is a singleton: There can be only one record of this
# content type.

accueil:
    name: accueil
    singular_name: accueil
    fields:
        title:
            type: text
            class: large
            group: content
            localize: true
            label: Title
            postfix: |
                The 'Homepage' can contain basic information about the website. This title will be
                shown on the homepage of the website, as the name implies. To change the
                <em><strong>name</strong></em> of the site, as is shown in the header, and the tab
                in the webbrowser, edit <code>sitename:</code> in the configuration file.
        image:
            type: image
        introduction:
            type: redactor
            localize: true
        content:
            type: redactor
            localize: true
        contentlink:
            type: text
            label: Link
            placeholder: 'contentType/slug or https://example.org/'
            postfix: "Use this to add a link for this Homepage. This could either be an 'internal' link like <tt>page//about</tt>, if you use a contentType/slug combination. Otherwise use a proper URL, like `https://example.org`."
            fixture_format: '{url}'
        slug:
            type: slug
            uses: title
            group: Meta
    viewless: false
    taxonomy: [ categories, tags, foobars ]
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"

savoirFaire:
    name: Nos savoir faire
    singular_name: Nos savoir faire
    slug: Nos savoir faire
    fields:
        title:
            type: text
            class: large
            label: Titre
            info: Titre de la page
            fixture_format: '{title}'
            group: Introduction
        teaser:
            type: redactor
            label: Texte d'introduction
            info: Texte d'introduction de la page
            fixture_format: '{teaser}'
            group: Introduction
        cardOne:
            type: set
            label: Première carte
            group: Cartes
            fields:
                image:
                    type: image
                    label: Image de la première carte
                    info: Image de la première carte
                text:
                  type: text
                  label: Texte de la première carte
                  info: Texte de la première carte
        cardTwo:
            type: set
            label: Deuxième carte
            group: Cartes
            fields:
                image:
                    type: image
                    label: Image de la deuxième carte
                    info: Image de la deuxième carte
                text:
                  type: text
                  label: Texte de la deuxième carte
                  info: Texte de la deuxième carte
        cardThree:
            type: set
            label: Troisième carte
            group: Cartes
            fields:
                image:
                    type: image
                    label: Image de la troisième carte
                    info: Image de la troisième carte
                text:
                  type: text
                  label: Texte de la troisième carte
                  info: Texte de la troisième carte
        keyFigureTitle:
            type: text
            label: Titre de la section 
            info: Titre de la section chiffres clés
            group: Chiffres clés
        keyFigureOne:
            type: set
            label: Premier chiffre clé
            group: Chiffres clés
            fields:
                image:
                  type: image
                  label: Nombre du premier chiffre clé
                  info: Nombre du premier chiffre clé
                text:
                  type: text
                  label: Texte du premier chiffre clé
                  info: Texte du premier chiffre clé
        keyFigureTwo:
            type: set
            label: Deuxième chiffre clé
            group: Chiffres clés
            fields:
                image:
                    type: image
                    label: Nombre du deuxième chiffre clé
                    info: Nombre du deuxième chiffre clé
                text:
                  type: text
                  label: Texte du deuxième chiffre clé
                  info: Texte du deuxième chiffre clé
        keyFigureThree:
            type: set
            label: Troisième chiffre clé
            group: Chiffres clés
            fields:
                image:
                    type: image
                    label: Nombre du troisième chiffre clé
                    info: Nombre du troisième chiffre clé
                text:
                  type: text
                  label: Texte du troisième chiffre clé
                  info: Texte du troisième chiffre clé
        keyFigureFour:
            type: set
            label: Quatrième chiffre clé
            group: Chiffres clés
            fields:
                image:
                    type: image
                    label: Nombre du quatrième chiffre clé
                    info: Nombre du quatrième chiffre clé
                text:
                  type: text
                  label: Texte du quatrième chiffre clé
                  info: Texte du quatrième chiffre clé
        seo:
            type: seo
            group: "Réglage SEO"
        slug:
            type: slug
            uses: title
            group: Meta
    default_status: published
    viewless: false
    singleton: true
    icon_many: "fa:brain"
    icon_one: "fa:brain"

nosValeurs:
    name: Nos valeurs
    singular_name: Nos valeurs
    slug: Nos valeurs
    fields:
        title:
            type: text
            class: large
            label: Titre
            info: Titre de la page
            fixture_format: '{title}'
            group: Introduction
        teaser:
            type: redactor
            label: Texte d'introduction
            info: Texte d'introduction de la page
            fixture_format: '{teaser}'
            group: Introduction
        contentValues:
            type: collection
            label: Nos valeurs
            group: Valeurs
            fields:
                contentValue:
                    type: set
                    label: Valeur
                    fields:
                        image:
                            type: image
                            label: Image de la valeur
                            info: Image de la valeur
                        text:
                            type: textarea
                            label: Texte de la valeur
                            info: Texte de la valeur
        seo:
            type: seo
            group: "Réglage SEO"
        slug:
            type: slug
            uses: title
            group: Meta
    default_status: published
    viewless: false
    singleton: true
    icon_many: "fa:fist-raised"
    icon_one: "fa:fist-raised"

nosEquipes:
    name: Nos équipes
    singular_name: Nos équipes
    slug: Nos équipes
    fields:
        title:
            type: text
            class: large
            label: Titre
            info: Titre de la page
            fixture_format: '{title}'
            group: Introduction
        teaser:
            type: redactor
            label: Texte d'introduction
            info: Texte d'introduction de la page
            fixture_format: '{teaser}'
            group: Introduction
        image:
            type: image
            label: Image d'illustration
            info: Image illustrant le texte d'introduction
            group: Introduction
        bottomImage:
            type: image
            label: Image en arrière plan
            info: Image en arrière plan de la page
            group: Partie basse
        cardTitle:
            type: text
            label: Titre de la carte
            info: Titre de la carte
            group: Partie basse
        cardText:
            type: textarea
            label: Texte de la carte
            info: Texte de la carte
            group: Partie basse
        seo:
            type: seo
            group: "Réglage SEO"
        slug:
            type: slug
            uses: title
            group: Meta
    default_status: published
    viewless: false
    singleton: true
    icon_many: "fa:users"
    icon_one: "fa:users"

nosRealisations:
    name: Nos réalisations
    singular_name: Réalisation
    slug: Nos réalisations
    fields:
        title:
          type: text
          label: Nom de la réalisation
          info: Nom de la réalisation
          group: Réalisation
        carousel:
          type: imagelist
          label: Images de la réalisation
          info: Images de la réalisation
          group: Réalisation
        video:
          type: embed
          label: Vidéo de la réalisation
          info: Inserez le lien youtube de la vidéo
          group: Réalisation
    default_status: published
    viewless: false
    icon_many: "fa:images"
    icon_one: "fa:images"

vosOptions:
    name: Vos options
    singular_name: Vos options
    slug: Vos options
    fields:
        nosRealisationsTitle:
            type: text
            label: Titre de la page Nos réalisations
            info: Titre de la page Nos réalisations
            group: Nos réalisations
        nosRealisationsText:
            type: textarea
            label: Texte de la page Nos réalisations
            info: Texte de la page Nos réalisations
            group: Nos réalisations
        nosPartenaires:
            type: imagelist
            label: Nos partenaires
            info: Nos partenaires
            group: Ils nous font confiance
    default_status: published
    viewless: true
    singleton: true
    icon_many: "fa:sliders-h"
    icon_one: "fa:sliders-h"

# Possible field types:
#
# text - varchar(256) - input type text.
# number - double - Input field for numbers, with `mode: integer` or `mode: float`
# imagelist - text (65kb) - Input type for imagelists. Add multiple images. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# embed - text (65kb) - embed widget for video and audio. Stored as JSON.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - wysiwyg element, which is parsed as Markdown text.
# date - datetime - date selector widget, with `mode: date` or `mode: datetime`
# email - text(65kb) - Input type for email.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)
# set - text (65kb) - Input type for sests. Group fields semantically into a combined set field.
# collection - text (65kb) - Input type for collections. Add multiple fields of different types. Useful for lists.
# data - text (65kb) - Read-only field, useful for storing (raw) data provided by an external source.
# hidden - text (65kb) - Regular text field, except it is hidden from the content editor.
# slug - text(65kb) - The slug for the record. Use with option `uses: [ title ]` to generate based on a title field.

# Using YAML repeated nodes
#
# YAML allows the defining of "repeated nodes". These allow you to define a 'node'
# with a 'key: &name' and referenced later with '<<: *name'
#
# Bolt allows you to define this with the special entry of '__nodes:' that itself
# won't create a ContentType, but will allow you to use it in actual ContentTypes
# to prevent repeating yourself.
#
# To achieve this, first create a key '__nodes:' and place it before your other contenttypes:
#__nodes:
#    field_defaults: &field_defaults
#        title:
#            type: text
#            class: large
#            group: main
#        slug:
#            type: slug
#            uses: title
#    template_defaults: &template_defaults
#        template:
#            type: templateselect
#            filter: '*.twig'
#            group: meta
#
# Then, as an example, you could create a ContentType with default fields, with
# an additional 'image' field.
#
#contenttypeabc:
#    name: ContentType Abc
#    slug: contenttypeabc
#    fields:
#        <<: *field_defaults
#        image:
#            type: image
#            attrib: title
#            extensions: [ gif, jpg, png ]
#        <<: *template_defaults
#    taxonomy: [ chapters ]
#    records_per_page: 10
#
# Alternatively, or additionally, you then can then create a ContentType with
# default fields, and a 'select' field, and a different 'templateselect' option.
#
#contenttypexyz:
#    name: ContentType Xyz
#    slug: contenttypexyz
#    fields:
#        <<: *field_defaults
#        selectfield:
#            type: select
#            values: [ none, foo, bar ]
#        template:
#            type: templateselect
#            filter: '*_xyz.twig'
#    taxonomy: [ tags ]
#    records_per_page: 20
