# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus
#


main:
  - label: Accueil
    title: Page d'accueil
    link: accueil
    class: homepage
  - label: Nos savoirs faire
    title: Nos savoirs faire
    link: nos-savoirs-faire
    class: savoir-faire
  - label: Nos valeurs
    title: Nos valeurs
    link: nos-valeurs
    class: nos-valeurs
  - label: Nos équipes
    title: Nos équipes
    link: nos-equipes
    class: nos-equipes
  - label: Nos réalisations
    title: Nos réalisations
    link: nos-realisation
    class: nos-realisation
  - label: Recrutements
    title: Recrutements
    link: recrutements
    class: recrutements
  - label: Contact
    title: Contact
    link: contact
    class: contact

ffooter:
  - label: Accueil
    title: Page d'accueil
    link: accueil
    class: homepage
  - label: Nos savoirs faire
    title: Nos savoirs faire
    link: nos-savoirs-faire
    class: savoir-faire
  - label: Nos valeurs
    title: Nos valeurs
    link: nos-valeurs
    class: nos-valeurs

sfooter:
  - label: Nos équipes
    title: Nos équipes
    link: nos-equipes
    class: nos-equipes
  - label: Nos réalisations
    title: Nos réalisations
    link: nos-realisation
    class: nos-realisation
  - label: Recrutements
    title: Recrutements
    link: recrutements
    class: recrutements