# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: Home
    title: This is the <b>first<b> menu item.
    link: accueil
    class: homepage
foo: bar
