# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template
    required: false

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true
    required: false

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]
    required: false

contrats:
    name: Contrats
    slug: contrats
    singular_name: Contrat
    singular_slug: contrat
    behaves_like: categories
    multiple: true
    options: [ CDI, CDD, Intérim, Stage, Alternance, Freelance, Indépendant ]
    required: false

nosRealisationsTags:
    name: Tags de la réalisation
    slug: nosRealisations
    singular_slug: Realisation
    behaves_like: tags
    postfix: "Commencez un nouveau tag en saisissant un caractère, valider le tag en appuyant sur entrée."
    allow_spaces: false
    required: false
