templates:
    form: partials/forms/_replyform.twig
    email: partials/mail/_replyEmail.twig
notification:
    enabled: true
    debug: false
    debug_address: houry9@gmail.com # Email address used when debug mode is enabled
    debug_smtp: false
    subject: Transvis - Réponse à votre message
    subject_prefix: '[Transvis]'
    replyto_name: Transvis               # Email addresses and names can be either the
    replyto_email: contact@transvis.fr                 # name of a field below or valid text.
    to_name: "{EMAIL}"
    to_email: "{EMAIL}"
    from_name: 'Transvis'
    from_email: contact@transvis.fr
feedback:
    success: Votre message a était envoyé.
    error: Il y a eu un problème lors de l'envoi de votre message. Veuillez réessayer.
fields:
    email:
        type: email
        options:
            required: true
            label: Adresse mail
            attr:
                placeholder: Email du contact ...
                id: email
            constraints: [ NotBlank, Email ]
    subject:
        type: text
        options:
            required: true
            label: Sujet
            attr:
                placeholder: Sujet du mail ...
            constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
    message:
        type: textarea
        options:
            required: true
            label: Votre message
            attr:
                placeholder: Votre message ...
    id:
        type: hidden
        options:
            required: true
    submit:
        type: submit
        options:
            label: Envoyer
            attr:
                class: button primary